FROM gcc

RUN apt-get update && apt-get install -y \
    build-essential \
    libtcmalloc-minimal4 \
    cmake \
    gfortran- \
    libboost-all-dev \
    make \
    libtbb-dev

COPY . /cache/
RUN mkdir -p /cache/cache-service/.build
WORKDIR /cache/cache-service/.build

RUN cmake .. && make

CMD ["./cache_service"]
